### ISSUE TITLE
userns_mode option is not honoured

### ISSUE THREAD

**Issue by vmsh0** [containers/podman-py#493]
Hi,

It seems like userns mode is not honoured by either podman-py or the podman API.

Running podman 4.9.3 on an up-to-date Ubuntu 24.04.1 LTS virtual machine.

```
$ cat /etc/sub{uid,gid}
[some random username]:100000:65536
containers:2147483647:2147483648
[some random username]:100000:65536
containers:2147483647:2147483648
```

When creating and running the same exact container with `podman-py` and with the Podman CLI, it is apparent that in the former case the `userns_mode='auto'` option is not honoured.

I attach this test case which shows the issue clearly: https://gist.github.com/vmsh0/f32b137b6d4bf1d3dbf5b6745e92911c

One unit test creates a container using `podman-py`: the test fails as after inspecting the container you can see that `UsernsMode` is empty. The other unit test creates the same container by calling the podman CLI: in this case, the test succeeds and you can see that `UsernsMode` is set to `'private'` as expected.

As far as I can see, this fails silently. I noticed the issue by pure chance while investigating a different problem. This might potentially have security implications, as users might be expecting their containers to run in a separate user namespace while they are really running in the root namespace.

**Comment by rhatdan** [comment]
Make sure the service side is restarted?

**Comment by vmsh0** [comment]
> Make sure the service side is restarted?

I apologize, but I'm not sure I understand what you mean. If you are asking me whether I tried to restart the service to check if it would fix it, I did.

In the meanwhile, I have also noticed that the `remove=True` option is ignored as well. This one is simpler: the option is [explicitly removed](https://github.com/containers/podman-py/blob/e79f4af138003aa13bec8b51338b547ebc27739d/podman/domain/containers_create.py#L379) before sending off the request. The REST API does have the respective flag, and hacking the value back into the request payload with the debugger results in the container being created (and then removed) with the correct option and the test passing. Is there a special reason why the `remove` option is filtered out? If not, would you accept a pull request to stop filtering it out?

Finally, while trying to mitigate the `remove=True` option being ignored and resulting in me needing to manually clean up containers between each run of the unit tests, I have attempted setting the `replace` option. While the API exposes it, `podman-py` does not handle that option. Would you accept a pull request to handle the `replace` option?

I apologize for reporting everything in this issue; please do let me know if I should split the three things (userns, remove, replace) into three different issues.

**Comment by vmsh0** [comment]
Again -- sorry for going off-topic. I was under the impression that the other issues might have been related, but I no longer think that's the case. I have addressed the other issues in additional issues/PRs.

To recap where we're at, the issue I'm reporting is that, as shown by [this minimal example](https://gist.github.com/vmsh0/f32b137b6d4bf1d3dbf5b6745e92911c), the userns_mode parameter is not being honored.

**Comment by vmsh0** [comment]
I have now submitted PR #499, which addresses the underlying reason for the flag not being honored.

**Comment by kortiene** [comment]
Confirming this bug is still alive on **podman-py 5.8.0 + podman 5.8.2** (a year after the original report), with a different `userns_mode` value: **`"keep-id"`**. So the bug class isn't specific to `"auto"`; the request-level user-namespace parameter is silently dropped across the board.

### Environment

- macOS 15 (Darwin 25.3.0) host driving a Linux VM via `podman machine`
- Inside the VM: Fedora CoreOS 43, podman 5.8.2, crun 1.25
- Host: `podman-py==5.8.0`, Python 3.12.2

### Minimal repro

```python
import podman

with podman.PodmanClient(base_url="unix:///var/folders/.../podman-machine-default-api.sock") as c:
    ctr = c.containers.create(
        image="alpine:3.20",
        command=["sleep", "60"],
        userns_mode="keep-id",
        read_only=True,
        tty=True,
    )
    ctr.start()
```

`podman inspect <id> --format '{{.HostConfig.UsernsMode}}'` reports **`private`** (i.e., the keep-id request was dropped silently).

By contrast, the CLI honours the same flag against the same daemon:

```bash
$ podman run --rm --userns=keep-id --read-only --tty alpine:3.20 sleep 60 &
$ podman inspect $(podman ps -lq) --format '{{.HostConfig.UsernsMode}}'
keep-id:uid=0,gid=0
```

### Downstream impact

The silent drop combines badly with `read_only=True`: on podman 5.8 + crun 1.25, starting the container fails with

```
crun: unlink /dev/console: Read-only file system: OCI runtime error
```

because the container ends up in a `private` userns where `/dev/console` setup interacts differently with the read-only rootfs than it would have under `keep-id`. The container never starts; the operator sees an OCI runtime error rather than a "userns ignored" hint.

I hit this driving rootless agent containers from a CLI supervisor ([`claw`](https://github.com/kortiene/claw)). On Linux + podman 4.9.3 (older crun) the same code worked — the bug existed but `read_only=True` wasn't fatal there. On macOS + `podman machine` it's a hard block, and the OCI error message gives no clue that the SDK is dropping the user-namespace parameter on the wire.

### Why this matters for #499

PR #499 fixes the `auto` flavour via the `idmappings` workaround. It would be useful to know whether the fix also covers `"keep-id"` (and `"keep-id:uid=…,gid=…"`), or whether the same `idmappings`-default treatment needs to be extended to those values. Happy to test PR #499 against the `keep-id` repro above on this macOS + podman-machine setup if that's useful.

In the meantime, a downstream **silent-drop warning** in `containers_create.py` whenever `userns_mode` is set but the request would lose it would prevent future "container started in `private` instead of what I asked for" surprises like this one, even before the structural fix lands.
